# Generated by Django 4.1.1 on 2022-11-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Eng.'), ('Electrical Engineering', 'Electrical Eng.'), ('Mechanical Engineering', 'Mechanical Eng.')], max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('Phd', 'Doctoral Program (PhD)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_course',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Eng.'), ('Electrical Engineering', 'Electrical Eng.'), ('Mechanical Engineering', 'Mechanical Eng.')], default='No Preference', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_degree',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('Phd', 'Doctoral Program (PhD)')], default='No Preference', max_length=128),
        ),
    ]
