# Generated by Django 4.1.1 on 2022-11-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Raleigh', 'Raleigh'), ('Durham', 'Durham'), ('Cary', 'Cary'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='general_location_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='have_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_rooms',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='rent_per_person',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Eng.'), ('Electrical Engineering', 'Electrical Eng.'), ('Mechanical Engineering', 'Mechanical Eng.')], max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('Phd', 'Doctoral Program (PhD)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_course',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Eng.'), ('Electrical Engineering', 'Electrical Eng.'), ('Mechanical Engineering', 'Mechanical Eng.')], default='No Preference', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_degree',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('Phd', 'Doctoral Program (PhD)')], default='No Preference', max_length=128),
        ),
    ]
