# Generated by Django 4.1.1 on 2022-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_city_profile_general_location_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('PhD', 'Doctoral Program (PhD)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_degree',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('PhD', 'Doctoral Program (PhD)')], default='No Preference', max_length=128),
        ),
    ]
