# Generated by Django 4.1.1 on 2022-12-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_number_of_roommates_alter_profile_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apartment_photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
