# Generated by Django 4.1.1 on 2022-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference_sleep',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Night Owl', 'Night Owl'), ('Early Bird', 'Early Bird')], default='No Preference', max_length=128),
        ),
    ]
