# Generated by Django 4.1.1 on 2022-12-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_apartment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
