# Generated by Django 4.1.1 on 2022-12-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apartment_photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Raleigh', 'Raleigh'), ('Durham', 'Durham'), ('Cary', 'Cary'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='drug',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ("Drink, but don't smoke", "Drink, but don't smoke"), ("Smoke, but don't drink", "Smoke, but don't drink"), ('Drink and smoke', 'Drink and smoke'), ('Neither', 'Neither')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='furnished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='general_location_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='have_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='neat',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ('Neat', 'Neat'), ('Messy', 'Messy')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_roommates',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_rooms',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_drug',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ("Drink, but don't smoke", "Drink, but don't smoke"), ("Smoke, but don't drink", "Smoke, but don't drink"), ('Drink and smoke', 'Drink and smoke'), ('Neither', 'Neither')], default='No Preference', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_neat',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Quiet', 'Quiet'), ('Energetic', 'Energetic')], default='No Preference', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_sleep',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Night Owl', 'Night Owl'), ('Early Bird', 'Early Bird')], default='No Preference', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_study',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Quiet', 'Quiet'), ('Energetic', 'Energetic')], default='No Preference', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='rent_per_person',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='roommate_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ('Night Owl', 'Night Owl'), ('Early Bird', 'Early Bird')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='study',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ('Quiet', 'Quiet'), ('Energetic', 'Energetic')], max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('PhD', 'Doctoral Program (PhD)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_degree',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Bachelors', 'Bachelors Program (BS)'), ('Masters', 'Masters Program (MS)'), ('PhD', 'Doctoral Program (PhD)')], default='No Preference', max_length=128),
        ),
    ]
