# Generated by Django 4.1.1 on 2022-12-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_lease_end_date_profile_lease_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='furnished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roommate_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_roommates',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('Other', 'Other')], max_length=100),
        ),
    ]
