# Generated by Django 4.1.1 on 2022-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_preference_sleep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drug',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ("Drink, but don't smoke", "Drink, but don't smoke"), ("Smoke, but don't drink", "Smoke, but don't drink"), ('Drink and smoke', 'Drink and smoke'), ('Neither', 'Neither')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='neat',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ('Neat', 'Neat'), ('Messy', 'Messy')], max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_drug',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ("Drink, but don't smoke", "Drink, but don't smoke"), ("Smoke, but don't drink", "Smoke, but don't drink"), ('Drink and smoke', 'Drink and smoke'), ('Neither', 'Neither')], default='No Preference', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_neat',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Quiet', 'Quiet'), ('Energetic', 'Energetic')], default='No Preference', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_study',
            field=models.CharField(choices=[('No Preference', 'No Preference'), ('Quiet', 'Quiet'), ('Energetic', 'Energetic')], default='No Preference', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='study',
            field=models.CharField(blank=True, choices=[('No Preference', 'No Preference'), ('Quiet', 'Quiet'), ('Energetic', 'Energetic')], max_length=128),
        ),
    ]
